# Generated by Django 4.0.3 on 2022-03-07 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicrater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emojis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('happy', models.BooleanField()),
                ('sad', models.BooleanField()),
                ('celebration', models.BooleanField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='artists',
            options={'verbose_name_plural': 'Artists'},
        ),
        migrations.AlterModelOptions(
            name='ratings',
            options={'verbose_name_plural': 'Ratings'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='ratings',
            name='emoji',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='musicrater.emojis'),
        ),
    ]
