# Generated by Django 4.0.3 on 2022-04-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicrater', '0003_remove_ratings_emoji_emojis_song_emojis_username_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emojis',
            options={'verbose_name_plural': 'Emojis'},
        ),
    ]
