# Generated by Django 4.0.3 on 2022-04-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicrater', '0008_rename_displayname_spotifyusers_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyusers',
            name='session_id',
            field=models.CharField(default='5e29a79d-613e-4885-bbfd-82d31cda1bea', max_length=50),
            preserve_default=False,
        ),
    ]
