# Generated by Django 4.0.3 on 2022-04-09 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicrater', '0005_spotifytoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyUsers',
            fields=[
                ('spotifyID', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('displayName', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refresh_token', models.CharField(max_length=150)),
                ('access_token', models.CharField(max_length=150)),
                ('expires_in', models.DateTimeField()),
                ('token_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'SpotifyUsers',
            },
        ),
        migrations.DeleteModel(
            name='SpotifyToken',
        ),
        migrations.AlterField(
            model_name='emojis',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicrater.spotifyusers'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicrater.spotifyusers'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
