# Generated by Django 4.0.3 on 2022-04-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicrater', '0006_spotifyusers_delete_spotifytoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyusers',
            name='access_token',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='spotifyusers',
            name='refresh_token',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='spotifyusers',
            name='spotifyID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
