# Generated by Django 4.0.3 on 2022-04-10 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicrater', '0007_rename_songurl_artists_url'),
        ('musicrater', '0009_spotifyusers_session_id'),
    ]

    operations = [
    ]
