# Generated by Django 4.0.3 on 2022-04-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicrater', '0010_merge_20220410_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artists',
            name='url',
        ),
        migrations.AddField(
            model_name='artists',
            name='trackId',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
