# Generated by Django 4.0.3 on 2022-04-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicrater', '0011_remove_artists_url_artists_trackid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emojis',
            name='song',
        ),
        migrations.RemoveField(
            model_name='emojis',
            name='username',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='username',
        ),
        migrations.AddField(
            model_name='ratings',
            name='artist',
            field=models.CharField(default='hello', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratings',
            name='user',
            field=models.CharField(default='user', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rating',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ratings',
            name='song',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Artists',
        ),
        migrations.DeleteModel(
            name='Emojis',
        ),
        migrations.DeleteModel(
            name='SpotifyUsers',
        ),
    ]
