# Generated by Django 4.0.3 on 2022-04-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicrater', '0012_remove_emojis_song_remove_emojis_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
