# Generated by Django 4.0.3 on 2022-04-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicrater', '0013_alter_ratings_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='artist',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='song',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
